### ISSUE TITLE
Visual position data for words is sometimes inaccurate

### ISSUE THREAD

**Issue by mfboulos** [HazyResearch/fonduer#166] opened 2018-09-28 15:08 UTC
**Description**

For some words, the visual position data (using sentence.top, for example) is not accurate. This falls outside of the domain of the edge case of sentences being next to the edge of a page or spanning over different pages; even in the middle of a page, two words that are aligned horizontally may end up having drastically different tops.

This seems to be mostly the case with top and bottom properties, or at least it is more reasonably easy to find out the discrepancies there.

**To Reproduce**

- Preprocess any document
- Query the Sentences in the Document, and save a slice of about 20 or so
- For each Sentence, print sentence.top and compare the values to the document

**Example**

"visit." was in a Document I parsed, for which sentence.bottom yielded [292, 154] and sentence.top yielded [282, 144]. It is clear they are visibly aligned on the bottom, instead of 138 pixels apart as the visual data suggests.

**Expected behavior**

For the example, we would expect sentence.bottom to yield almost identical values. As for the rest of the data, it seems very inconsistent. Some sentences offer a very accurate representation of each word's position, some suggest that words are spread hundreds of pixels apart when they are aligned.

**Environment**

 - OS: Ubuntu 16.04
 - PostgreSQL Version: 9.5.14
 - Fonduer Version: 0.3.2

**Comment by mfboulos** [comment] 2018-09-28 18:13
No, the document I used contains proprietary data. I suggest using a document primarily formatted into tables, I don't know for sure if that was the primary cause since the entire document was made of tables, but it might be a good starting point.

**Comment by Prabh06** [comment] 2018-10-01 09:15
@lukehsiao I have also faced this issue while visualizing nodes/mentions in tables. Here is the sample doc [data.zip](https://github.com/HazyResearch/fonduer/files/2433377/data.zip)

**Comment by DoraEx** [comment] 2018-10-31 17:44
Having the same issue. I've been trying to check horizontal alignment using the top and bottom properties of the words in a sentence, but sometimes the words in the same sentence have very large differences in their values. Also, sometimes the page number for some or all of the words are wrong. It most commonly happens to words near the top or bottom of a page, but that is not always the case.

**Comment by SenWu** [comment] 2018-10-31 18:18
Thanks @DoraEx @Prabh06 @mfboulos for your information. We are checking that now. To share you more information, we use Poppler to extract the coordinates of words and align word from users' input with coordinates from Poppler in [visual_linker](https://github.com/HazyResearch/fonduer/blob/master/src/fonduer/parser/visual_linker.py) and sometimes they are not perfectly matching and we use fuzzy matching. I think that's the part causes the issue. Will keep you posted!

**Comment by HiromuHota** [comment] 2019-04-12 17:11
This issue can be reproduced by one of the example docs that is used for testing (ie `tests/data/html_simple/diseases.html` and `tests/data/pdf_simple/diseases.pdf`).

The following two asserts in a unit test (`tests.parser.test_parser.test_parse_document_diseases`) are actually wrong.
https://github.com/HazyResearch/fonduer/blob/a28bc45ccdf06166d2f781a61952717d05053147/tests/parser/test_parser.py#L547-L548

`print(sentence)` gives `Sentence (Doc: 'diseases', Table: 0, Row: 2, Col: 1, Index: 10, Text: '-Dublin to Milwaukee')`

So you can see that this `sentence` refers to the one next to 2001 in the following image:
![image](https://user-images.githubusercontent.com/20668349/56053786-dd46bc00-5d09-11e9-92bb-1ecdcb179cd4.png)

Therefore, the assertions should be as follows:
```
assert sentence.top == [342, 342, 356] 
assert sentence.left == [318, 358, 318]
```

Why does the test not fail? This is because the visual_linker mis-links "to" with the one at (369, 296) instead of one at (358, 342).

**Comment by HiromuHota** [comment] 2020-09-22 21:49
Duplicate of #12

**Closed by HiromuHota** 2020-09-22 21:49 UTC
Labels: bug, help wanted, needs-info
