### ISSUE TITLE
Duplicate key error while adding two mentions which are same

### ISSUE THREAD

**Issue by saikalyan9981** [HazyResearch/fonduer#501] opened 2020-08-29 11:37 UTC
Suppose that I have two mentions (say for example zip-code and  tax code) whose matchers return true (checking 5 digit regex match for both mentions) for the same span in document, then I think Fonduer is throwing this error. please help me in resolving this.
```

sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "context_stable_id_key"
DETAIL:  Key (stable_id)=(1443208965_10_subset::span_mention:23313:23321) already exists.

[SQL: INSERT INTO context (type, stable_id) VALUES (%(type)s, %(stable_id)s) RETURNING context.id]
```

**Comment by saikalyan9981** [comment] 2020-08-29 12:20
Note that this was happening because I was using a different MentionExtractor for the two mentions.

**Comment by HiromuHota** [comment] 2020-08-31 16:36
What would happen if you use only one MentionExtractor for the two mentions?

**Comment by saikalyan9981** [comment] 2020-08-31 23:56
I need two mention Extractors in my program because first I'm extracting some candidates with certain matchers and labelling functions, and based on those candidates extracted, I need to extract some other candidates, in next round.
Do you think it's bad to have such a pipeline?

**Comment by HiromuHota** [comment] 2020-09-01 00:00
I'm not saying this is a bad idea or not. I'm just trying to understand the issue.
From your response, seems that you've never tried to extract these two mentions with a single MentionExtractor.

Which version of Fonduer are you using?

**Comment by saikalyan9981** [comment] 2020-09-01 00:25
I'm using "0.8.2". I'm using a singleMentionExtractor for 4 mentions in the first run. I need to have those mentions extracted to extract other mentions in my second run, so using a second mention extractor.

**Comment by HiromuHota** [comment] 2020-09-01 01:54
> If I use a single extractor for all mentions, it's giving no errors for the same context match.

@saikalyan9981 Thanks for this valuable information! I'll look into this.
Meanwhile, you could use a single extractor as a workaround if the second extraction does not depend on the first one.

**Comment by HiromuHota** [comment] 2020-09-04 23:42
I found that this issue is a regression caused by #368.
A workaround would be to set `clear=False` like `mention_extractor.apply(clear=False, ...)`.
@saikalyan9981 can you try this workaround? Please let me know how it works.

**Comment by HiromuHota** [comment] 2020-09-05 00:05
I think this issue is similar (not identical) to #424.
You will have an error even when you set `clear=True`.
A workaround would be to downgrade to v0.7.1 or to upgrade to v0.8.3, which is not released yet.

**Comment by HiromuHota** [comment] 2020-09-22 21:53
Closing as v0.8.3 has been released.

**Closed by HiromuHota** 2020-09-22 21:53 UTC
